[build]
  command = "npm run build"
  publish = "build/"

[[redirects]]
  status = 404
  from = "/*"
  to = "/index.html"

[[redirects]]
  status = 404
  from = "/catatan/*"
  to = "/catatan/index.html"

[[redirects]]
  status = 500
  from = "/*"
  to = "/500/index.html"