[build]
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  publish = "build"

[build.environment ]
  NODE_VERSION = "16.14.0"

[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.js]
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
  status = 404
  from = "/*"
  to = "/"
#
#[[redirects]]
#  status = 500
#  from = "/*"
#  to = "/500/"

[[redirects]]
  status = 404
  from = "/catatan/*"
  to = "/catatan"