[build]
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  publish = "build/"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://dan.my.id"

[[plugins]]
  package = "netlify-plugin-webmentions"

	[plugins.inputs]
    baseUrl = "https://dan.my.id"
