backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://dan.my.id
logo_url: https://dan.my.id/logo.svg

locale: 'id'

# These lines should *not* be indented
media_folder: 'static/images' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'src/content/blogs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{num}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'No.', name: 'num', widget: 'number' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Tags', name: 'tags', widget: 'list', min: 1 }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'page' # Used in routes, e.g., /admin/collections/blog
    label: 'Page' # Used in the UI
    folder: 'src/content/pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Tags', name: 'tags', widget: 'list', min: 1 }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
